# Generated by Django 2.0.2 on 2020-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
